// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Bindings {
  IMAGE_GENERATION_WORKFLOWS: any;
  IMAGE_GEN_WORKFLOW: any;
  SVG_BUCKET: any;
  IMAGE_QUEUE_PUBLISH: any;
  PNG_BUCKET: any;
	GOOGLE_FONTS: string;
}
